apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://my-cluster-api-server:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t...
users:
- name: my-user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t...
    client-key-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t... //cat 檔案路徑 | base64 -w 0
contexts: # user 與 cluster關聯
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
